# Generated by Django 5.2.17 on 2026-09-21 00:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('topic', models.CharField(choices=[('booking', "A booking I've made"), ('trip', 'A question about a trip'), ('group', 'Group or corporate travel'), ('partner', 'Partnerships'), ('other', 'Something else')], default='other', max_length=20)),
                ('booking_reference', models.CharField(blank=True, max_length=12)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('staff_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'support message',
                'ordering': ('is_resolved', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(default='footer', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'newsletter subscriber',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('handle', models.CharField(blank=True, help_text='Social handle shown under the name.', max_length=60)),
                ('trip_taken', models.CharField(blank=True, max_length=120)),
                ('quote', models.TextField(max_length=400)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('avatar_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
