# Generated by Django 5.2.17 on 2026-09-21 00:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalogue/')),
                ('image_url', models.URLField(blank=True, help_text='Optional. Used when no file is uploaded — handy for seed data.')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
                ('emoji', models.CharField(blank=True, help_text='Shown on category chips, e.g. 🏔️', max_length=8)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalogue/')),
                ('image_url', models.URLField(blank=True, help_text='Optional. Used when no file is uploaded — handy for seed data.')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('country', models.CharField(max_length=80)),
                ('region', models.CharField(blank=True, help_text='State or province', max_length=80)),
                ('tagline', models.CharField(blank=True, help_text='One line shown on cards and the hero.', max_length=140)),
                ('description', models.TextField()),
                ('best_time_to_visit', models.CharField(blank=True, max_length=120)),
                ('latitude', models.FloatField(blank=True, help_text='Used to place the pin on the 3D globe.', null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['slug'], name='destination_slug_528bb8_idx'), models.Index(fields=['country'], name='destination_country_2ade19_idx')],
            },
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('image_url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='destinations.destination')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalogue/')),
                ('image_url', models.URLField(blank=True, help_text='Optional. Used when no file is uploaded — handy for seed data.')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('summary', models.CharField(help_text='One line shown on trip cards.', max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Full price per person.', max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty if the trip is not on offer.', max_digits=10, null=True)),
                ('duration_days', models.PositiveSmallIntegerField(default=3)),
                ('duration_nights', models.PositiveSmallIntegerField(default=2)),
                ('max_guests', models.PositiveSmallIntegerField(default=12)),
                ('min_guests', models.PositiveSmallIntegerField(default=1)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy — anyone can do this'), ('moderate', 'Moderate — some walking and early starts'), ('challenging', 'Challenging — good fitness needed')], default='easy', max_length=20)),
                ('inclusions', models.TextField(blank=True, help_text='One item per line — shown as a checklist.')),
                ('exclusions', models.TextField(blank=True, help_text='One item per line.')),
                ('highlights', models.TextField(blank=True, help_text='One highlight per line.')),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_to', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide this trip from the site.')),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('categories', models.ManyToManyField(blank=True, related_name='packages', to='destinations.category')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'trip package',
                'ordering': ('-is_featured', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('meals', models.CharField(blank=True, help_text='e.g. Breakfast, dinner', max_length=120)),
                ('stay', models.CharField(blank=True, help_text='Where guests sleep', max_length=140)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='destinations.package')),
            ],
            options={
                'verbose_name': 'itinerary day',
                'verbose_name_plural': 'itinerary days',
                'ordering': ('day_number',),
            },
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('image_url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='destinations.package')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['slug'], name='destination_slug_7d089d_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['price'], name='destination_price_d500ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itineraryday',
            unique_together={('package', 'day_number')},
        ),
    ]
